<?php
/*
 * Copyright © 2022 Beehexa All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 *
 * @var $escaper Escaper
 * @var $block RegisterStore
 */

use Beehexa\HexaSync\Block\System\Config\Form\Field\RegisterStore;
use Magento\Framework\Escaper;

?>
<button class="scalable" type="button" id="<?= $block->getHtmlId() ?>"
    <?= $block->getDisabled() ? 'disabled' : '' ?> data-mage-init='{"beehexaGenerateIntegration":{
    "url": "<?= $escaper->escapeUrl($block->getAjaxUrl()) ?>",
    "elementId": "<?= $block->getHtmlId() ?>",
    "successText": "<?= $escaper->escapeHtmlAttr(__('Successful!')) ?>",
    "failedText": "<?= $escaper->escapeHtmlAttr(__('Re-Generation failed! Try again?')) ?>"}}'>
    <span id="<?= $block->getHtmlId() ?>_result"><?= $escaper->escapeHtml($block->getButtonLabel()) ?></span>
</button>
